# Generated by Django 4.1.7 on 2023-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дискорд'),
        ),
    ]
