# Generated by Django 4.1.7 on 2023-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.CharField(choices=[('live', 'Live'), ('cached', 'Cached'), ('github', 'Github')], default=0, max_length=255, verbose_name='Куда ведет ссылка'),
            preserve_default=False,
        ),
    ]
