# Generated by Django 4.1.7 on 2023-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('projects', '0004_alter_link_options_alter_link_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(related_name='projects', to='links.link'),
        ),
    ]
