# Generated by Django 4.1.7 on 2023-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название скилла')),
                ('type', models.CharField(choices=[('languages', 'Языки'), ('databases', 'Базы данных'), ('tools', 'Инструменты'), ('frameworks', 'Фреймворки'), ('other', 'Другие')], default='languages', max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
            },
        ),
    ]
